services:
  frontend:
    container_name: webster-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:6767/webster/v1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
